# Generated by Django 5.2.9 on 2025-12-25 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("PASSIVE", "Pasif"),
                            ("COMPLETED", "Tamamladı"),
                            ("DROPPED", "Bıraktı"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınıf Kaydı",
                "verbose_name_plural": "Sınıf Kayıtları",
            },
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Sınıf Adı")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Sınıf Kodu"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ACADEMIC", "Akademik"), ("VOCATIONAL", "Mesleki")],
                        default="ACADEMIC",
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("COMPLETED", "Tamamlandı"),
                            ("ARCHIVED", "Arşivlendi"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "term",
                    models.CharField(blank=True, max_length=50, verbose_name="Dönem"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=50, verbose_name="Kapasite"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Başlangıç"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        related_name="teaching_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eğitmenler",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="enrolled_classes",
                        through="student.ClassEnrollment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenciler",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="tenants.tenant",
                        verbose_name="Akademi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınıf",
                "verbose_name_plural": "Sınıflar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="student.classgroup",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("due_date", models.DateTimeField(verbose_name="Teslim Tarihi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("PUBLISHED", "Yayında"),
                            ("CLOSED", "Kapalı"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Maksimum Puan"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="Ekler"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="student.classgroup",
                        verbose_name="Sınıf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödev",
                "verbose_name_plural": "Ödevler",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("scheduled_at", models.DateTimeField(verbose_name="Planlanan Zaman")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="Süre (dk)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Planlandı"),
                            ("LIVE", "Canlı"),
                            ("COMPLETED", "Tamamlandı"),
                            ("CANCELLED", "İptal"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("meeting_url", models.URLField(blank=True, verbose_name="Ders URL")),
                (
                    "recording_url",
                    models.URLField(blank=True, verbose_name="Kayıt URL"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Maks Katılımcı"
                    ),
                ),
                (
                    "participant_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Katılımcı Sayısı"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="student.classgroup",
                        verbose_name="Sınıf",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Canlı Ders",
                "verbose_name_plural": "Canlı Dersler",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Konu"),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="student.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesaj",
                "verbose_name_plural": "Mesajlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(blank=True, verbose_name="Mesaj")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "Sistem"),
                            ("ASSIGNMENT", "Ödev"),
                            ("LIVE", "Canlı Ders"),
                            ("GRADE", "Not"),
                            ("MESSAGE", "Mesaj"),
                            ("ANNOUNCEMENT", "Duyuru"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Kaynak"),
                ),
                (
                    "action_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Link"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Teknik"),
                            ("ACADEMIC", "Akademik"),
                            ("BILLING", "Ödeme"),
                            ("OTHER", "Diğer"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Açık"),
                            ("ANSWERED", "Cevaplandı"),
                            ("CLOSED", "Kapatıldı"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="Cevap")),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Talebi",
                "verbose_name_plural": "Destek Talepleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("SUBMITTED", "Teslim Edildi"),
                            ("LATE", "Geç Teslim"),
                            ("GRADED", "Notlandırıldı"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="İçerik")),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="Dosyalar"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Puan"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Geri Bildirim"),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="student.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödev Teslimi",
                "verbose_name_plural": "Ödev Teslimleri",
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="classenrollment",
            unique_together={("user", "class_group")},
        ),
    ]
