# Generated by Django 5.2.9 on 2025-12-26 21:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "video_timecode",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quiz'in gösterileceği video zamanı",
                        null=True,
                        verbose_name="Video Zamanı (sn)",
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70,
                        help_text="Minimum geçme puanı (0-100)",
                        max_digits=5,
                        verbose_name="Geçme Puanı",
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Boş bırakılırsa süresiz",
                        null=True,
                        verbose_name="Süre Limiti (dk)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = sınırsız",
                        verbose_name="Maksimum Deneme",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="Soruları Karıştır"
                    ),
                ),
                (
                    "shuffle_options",
                    models.BooleanField(
                        default=False, verbose_name="Seçenekleri Karıştır"
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True,
                        help_text="Quiz bittikten sonra",
                        verbose_name="Doğru Cevapları Göster",
                    ),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="Geçilmeden sonraki içerik açılmaz",
                        verbose_name="İlerlemeyi Engeller",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        help_text="Video içi quiz için",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz'ler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Başladı"),
                            ("in_progress", "Devam Ediyor"),
                            ("submitted", "Gönderildi"),
                            ("graded", "Notlandırıldı"),
                            ("expired", "Süresi Doldu"),
                        ],
                        default="started",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Puan"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Maksimum Puan",
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Geçti")),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Başlangıç"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderilme"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Süre Bitiş"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to="player.playbacksession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Denemesi",
                "verbose_name_plural": "Quiz Denemeleri",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Çoktan Seçmeli"),
                            ("multi", "Çoklu Seçim"),
                            ("truefalse", "Doğru/Yanlış"),
                            ("short", "Kısa Cevap"),
                        ],
                        default="mcq",
                        max_length=20,
                        verbose_name="Soru Türü",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Soru")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["A seçeneği", "B seçeneği", ...]',
                        verbose_name="Seçenekler",
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        help_text='mcq: "A", multi: ["A", "B"], truefalse: true/false, short: "cevap"',
                        verbose_name="Doğru Cevap",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Cevap sonrası gösterilen açıklama",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=5, verbose_name="Puan"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Sorusu",
                "verbose_name_plural": "Quiz Soruları",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "answer",
                    models.JSONField(blank=True, null=True, verbose_name="Cevap"),
                ),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="Doğru"),
                ),
                (
                    "points_awarded",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Verilen Puan",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cevaplanma"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.quizattempt",
                        verbose_name="Deneme",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.quizquestion",
                        verbose_name="Soru",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Cevabı",
                "verbose_name_plural": "Quiz Cevapları",
                "ordering": ["question__order"],
            },
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["tenant", "course"], name="quizzes_qui_tenant__ee3500_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["tenant", "content"], name="quizzes_qui_tenant__cbcefd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["tenant", "quiz", "user"], name="quizzes_qui_tenant__83b891_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["tenant", "user", "-started_at"],
                name="quizzes_qui_tenant__618457_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["quiz", "order"], name="quizzes_qui_quiz_id_8d38bc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="unique_attempt_question"
            ),
        ),
    ]
