# Generated by Django 5.2.9 on 2025-12-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Çoktan Seçmeli"),
                    ("multi", "Çoklu Seçim"),
                    ("truefalse", "Doğru/Yanlış"),
                    ("short", "Kısa Cevap"),
                    ("matching", "Eşleştirme"),
                ],
                default="mcq",
                max_length=20,
                verbose_name="Soru Türü",
            ),
        ),
    ]
