# Generated by Django 5.2.9 on 2025-12-26 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteExport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, null=True, verbose_name="Dosya URL"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Zamanı"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_exports",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not Dışa Aktarma",
                "verbose_name_plural": "Not Dışa Aktarmaları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoNote",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("note", "Not"),
                            ("question", "Soru"),
                            ("highlight", "Önemli"),
                            ("bookmark", "Yer İşareti"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="Not Türü",
                    ),
                ),
                ("content_text", models.TextField(blank=True, verbose_name="İçerik")),
                (
                    "video_ts",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Notun ilişkili olduğu video zamanı",
                        null=True,
                        verbose_name="Video Zamanı (sn)",
                    ),
                ),
                (
                    "video_ts_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Highlight için bitiş zamanı",
                        null=True,
                        verbose_name="Bitiş Zamanı (sn)",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Özel"),
                            ("group", "Grup"),
                            ("public", "Herkese Açık"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Görünürlük",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Paylaşım Tokeni",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Highlight/not rengi (hex)",
                        max_length=20,
                        null=True,
                        verbose_name="Renk",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiketler"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Sabitlenmiş"),
                ),
                (
                    "reply_count",
                    models.PositiveIntegerField(default=0, verbose_name="Cevap Sayısı"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Beğeni Sayısı"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="player.playbacksession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Notu",
                "verbose_name_plural": "Video Notları",
                "ordering": ["video_ts", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteReply",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_text", models.TextField(verbose_name="İçerik")),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Beğeni Sayısı"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="notes.notereply",
                        verbose_name="Üst Cevap",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notes.videonote",
                        verbose_name="Not",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not Cevabı",
                "verbose_name_plural": "Not Cevapları",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteReaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Beğeni"),
                            ("bookmark", "Yer İşareti"),
                            ("helpful", "Yardımcı"),
                        ],
                        max_length=20,
                        verbose_name="Reaksiyon",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="notes.notereply",
                        verbose_name="Cevap",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="notes.videonote",
                        verbose_name="Not",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not Reaksiyonu",
                "verbose_name_plural": "Not Reaksiyonları",
            },
        ),
        migrations.AddIndex(
            model_name="videonote",
            index=models.Index(
                fields=["tenant", "user", "content"],
                name="notes_video_tenant__22f013_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videonote",
            index=models.Index(
                fields=["content", "visibility", "video_ts"],
                name="notes_video_content_83d1be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videonote",
            index=models.Index(
                fields=["tenant", "course", "visibility"],
                name="notes_video_tenant__2c341a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notereply",
            index=models.Index(
                fields=["note", "created_at"], name="notes_noter_note_id_09d4a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notereaction",
            index=models.Index(
                fields=["user", "note"], name="notes_noter_user_id_1361d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notereaction",
            index=models.Index(
                fields=["user", "reply"], name="notes_noter_user_id_cd2be1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("note__isnull", False)),
                fields=("user", "note", "reaction_type"),
                name="unique_note_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="notereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reply__isnull", False)),
                fields=("user", "reply", "reaction_type"),
                name="unique_reply_reaction",
            ),
        ),
    ]
