# Generated by Django 5.2.9 on 2025-12-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Akademi Adı")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL yapısında kullanılacak (örn: ibb-tech)",
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "logo",
                    models.URLField(
                        blank=True,
                        help_text="Akademi logosu URL'i",
                        verbose_name="Logo URL",
                    ),
                ),
                ("favicon", models.URLField(blank=True, verbose_name="Favicon URL")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Municipality", "Belediye"),
                            ("Corporate", "Kurumsal"),
                            ("University", "Üniversite"),
                            ("Government", "Kamu Kurumu"),
                            ("NGO", "Sivil Toplum Kuruluşu"),
                        ],
                        default="Corporate",
                        max_length=20,
                        verbose_name="Akademi Türü",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Web Sitesi")),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Hex renk kodu (örn: #4F46E5)",
                        max_length=7,
                        verbose_name="Ana Renk",
                    ),
                ),
                (
                    "sidebar_position",
                    models.CharField(
                        choices=[("left", "Sol"), ("right", "Sağ")],
                        default="left",
                        max_length=10,
                        verbose_name="Sidebar Konumu",
                    ),
                ),
                (
                    "sidebar_color",
                    models.CharField(
                        default="#1E293B", max_length=7, verbose_name="Sidebar Rengi"
                    ),
                ),
                (
                    "sidebar_content_color",
                    models.CharField(
                        default="#F8FAFC",
                        max_length=7,
                        verbose_name="Sidebar İçerik Rengi",
                    ),
                ),
                (
                    "main_background_color",
                    models.CharField(
                        default="#F1F5F9",
                        max_length=7,
                        verbose_name="Ana Arkaplan Rengi",
                    ),
                ),
                (
                    "button_radius",
                    models.CharField(
                        choices=[
                            ("rounded-none", "Köşeli"),
                            ("rounded-md", "Orta"),
                            ("rounded-xl", "Yuvarlak"),
                            ("rounded-full", "Tam Yuvarlak"),
                        ],
                        default="rounded-md",
                        max_length=20,
                        verbose_name="Buton Yuvarlaklığı",
                    ),
                ),
                (
                    "storage_limit_gb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Depolama Limiti (GB)"
                    ),
                ),
                (
                    "user_limit",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="0 = sınırsız",
                        verbose_name="Kullanıcı Limiti",
                    ),
                ),
                (
                    "course_limit",
                    models.PositiveIntegerField(
                        default=50, help_text="0 = sınırsız", verbose_name="Kurs Limiti"
                    ),
                ),
                (
                    "module_live_class",
                    models.BooleanField(default=True, verbose_name="Canlı Ders Modülü"),
                ),
                (
                    "module_quiz",
                    models.BooleanField(default=True, verbose_name="Quiz Modülü"),
                ),
                (
                    "module_exam",
                    models.BooleanField(default=True, verbose_name="Sınav Modülü"),
                ),
                (
                    "module_assignment",
                    models.BooleanField(default=True, verbose_name="Ödev Modülü"),
                ),
                (
                    "module_certificate",
                    models.BooleanField(default=True, verbose_name="Sertifika Modülü"),
                ),
                (
                    "module_forum",
                    models.BooleanField(default=False, verbose_name="Forum Modülü"),
                ),
                (
                    "module_ai_assistant",
                    models.BooleanField(
                        default=False, verbose_name="AI Asistan Modülü"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Doğrulanmış"),
                ),
                (
                    "stats_users",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Kullanıcı"
                    ),
                ),
                (
                    "stats_courses",
                    models.PositiveIntegerField(default=0, verbose_name="Toplam Kurs"),
                ),
                (
                    "stats_storage_used_mb",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kullanılan Depolama (MB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deneme Süresi Bitiş"
                    ),
                ),
            ],
            options={
                "verbose_name": "Akademi",
                "verbose_name_plural": "Akademiler",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_ten_slug_63daca_idx"),
                    models.Index(
                        fields=["is_active"], name="tenants_ten_is_acti_8f654a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_from_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Gönderen Adı"
                    ),
                ),
                (
                    "email_from_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Gönderen E-posta"
                    ),
                ),
                (
                    "allow_self_registration",
                    models.BooleanField(
                        default=False,
                        help_text="Kullanıcılar kendi kendilerine kayıt olabilir mi?",
                        verbose_name="Kendi Kendine Kayıt",
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True, verbose_name="E-posta Doğrulaması Zorunlu"
                    ),
                ),
                (
                    "default_user_role",
                    models.CharField(
                        default="STUDENT",
                        max_length=20,
                        verbose_name="Varsayılan Kullanıcı Rolü",
                    ),
                ),
                (
                    "require_course_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Eğitmenlerin kursları yayınlamadan önce onay gereksin mi?",
                        verbose_name="Kurs Onayı Zorunlu",
                    ),
                ),
                (
                    "default_course_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Herkese Açık"),
                            ("private", "Özel"),
                            ("unlisted", "Listelenmemiş"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Varsayılan Kurs Görünürlüğü",
                    ),
                ),
                (
                    "certificate_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Örn: CERT, AKD",
                        max_length=20,
                        verbose_name="Sertifika Ön Eki",
                    ),
                ),
                (
                    "certificate_template",
                    models.TextField(
                        blank=True, verbose_name="Sertifika Şablonu (HTML)"
                    ),
                ),
                ("custom_css", models.TextField(blank=True, verbose_name="Özel CSS")),
                (
                    "custom_js",
                    models.TextField(blank=True, verbose_name="Özel JavaScript"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akademi Ayarları",
                "verbose_name_plural": "Akademi Ayarları",
            },
        ),
    ]
