# Generated by Django 5.2.9 on 2025-12-29 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("storage", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planlı Ders"),
                            ("adhoc", "Anlık Toplantı"),
                            ("webinar", "Webinar"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("scheduled", "Planlandı"),
                            ("live", "Yayında"),
                            ("ended", "Bitti"),
                            ("cancelled", "İptal"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(verbose_name="Planlanan Başlangıç"),
                ),
                ("scheduled_end", models.DateTimeField(verbose_name="Planlanan Bitiş")),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gerçek Başlangıç"
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gerçek Bitiş"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("jitsi", "Jitsi Meet"),
                            ("bbb", "BigBlueButton"),
                            ("zoom", "Zoom"),
                        ],
                        default="jitsi",
                        max_length=20,
                        verbose_name="Sağlayıcı",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Oda ID",
                    ),
                ),
                ("room_url", models.URLField(blank=True, verbose_name="Oda URL")),
                (
                    "room_password",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Oda Şifresi"
                    ),
                ),
                (
                    "moderator_url",
                    models.URLField(
                        blank=True,
                        help_text="BBB için moderatör giriş URL'i",
                        verbose_name="Moderatör URL",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Maksimum Katılımcı"
                    ),
                ),
                (
                    "recording_enabled",
                    models.BooleanField(default=True, verbose_name="Kayıt Aktif"),
                ),
                (
                    "auto_recording",
                    models.BooleanField(
                        default=False,
                        help_text="Ders başladığında otomatik kayıt başlat",
                        verbose_name="Otomatik Kayıt",
                    ),
                ),
                (
                    "waiting_room_enabled",
                    models.BooleanField(default=True, verbose_name="Bekleme Odası"),
                ),
                (
                    "students_can_share_screen",
                    models.BooleanField(
                        default=False, verbose_name="Öğrenci Ekran Paylaşımı"
                    ),
                ),
                (
                    "students_start_muted",
                    models.BooleanField(
                        default=True, verbose_name="Öğrenci Sessiz Başlasın"
                    ),
                ),
                (
                    "students_video_off",
                    models.BooleanField(
                        default=False, verbose_name="Öğrenci Kamera Kapalı"
                    ),
                ),
                (
                    "participant_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Katılımcı"
                    ),
                ),
                (
                    "peak_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="En Yüksek Katılımcı"
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Süre (dk)"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        help_text="İlişkili kurs içeriği (opsiyonel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sessions",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_live_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canlı Ders",
                "verbose_name_plural": "Canlı Dersler",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="LiveSessionArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("whiteboard", "Whiteboard"),
                            ("chat", "Sohbet"),
                            ("file", "Dosya"),
                            ("poll", "Anket"),
                            ("notes", "Notlar"),
                            ("shared_notes", "Paylaşılan Notlar"),
                        ],
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="JSON veya text (chat için)",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Ek Veri"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_artifacts",
                        to="storage.fileupload",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="live.livesession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oturum Çıktısı",
                "verbose_name_plural": "Oturum Çıktıları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSessionAttendanceSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Süre (sn)"
                    ),
                ),
                (
                    "join_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Kaç kez katıldı",
                        verbose_name="Katılım Sayısı",
                    ),
                ),
                ("first_join", models.DateTimeField(verbose_name="İlk Katılım")),
                (
                    "last_leave",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Ayrılış"
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(
                        default=False,
                        help_text="Eşik değeri geçti mi?",
                        verbose_name="Katıldı",
                    ),
                ),
                (
                    "attendance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Katılım Yüzdesi",
                    ),
                ),
                (
                    "late_join",
                    models.BooleanField(default=False, verbose_name="Geç Katılım"),
                ),
                (
                    "early_leave",
                    models.BooleanField(default=False, verbose_name="Erken Ayrılış"),
                ),
                (
                    "background_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Arka Plan Süresi (sn)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="live.livesession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_attendance_summaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Katılım Özeti",
                "verbose_name_plural": "Katılım Özetleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSessionParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Eğitmen"),
                            ("moderator", "Moderatör"),
                            ("participant", "Öğrenci"),
                        ],
                        default="participant",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("joined_at", models.DateTimeField(verbose_name="Katılım Zamanı")),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ayrılma Zamanı"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Süre (sn)"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="mobile, desktop, tablet",
                        max_length=50,
                        verbose_name="Cihaz Türü",
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tarayıcı"
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="KVKK uyumu için IP hash'i",
                        max_length=64,
                        verbose_name="IP Hash",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Şu anda oturumda mı?",
                        verbose_name="Aktif",
                    ),
                ),
                ("kicked", models.BooleanField(default=False, verbose_name="Atıldı")),
                (
                    "kick_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Atılma Nedeni"
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Heartbeat"
                    ),
                ),
                (
                    "background_duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sekme arka plandayken geçen süre",
                        verbose_name="Arka Plan Süresi (sn)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="live.livesession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_session_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oturum Katılımcısı",
                "verbose_name_plural": "Oturum Katılımcıları",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSessionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recording_required",
                    models.BooleanField(default=True, verbose_name="Kayıt Zorunlu"),
                ),
                (
                    "auto_recording",
                    models.BooleanField(default=False, verbose_name="Otomatik Kayıt"),
                ),
                (
                    "recording_retention_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Kayıt Saklama Süresi (gün)"
                    ),
                ),
                (
                    "attendance_threshold_percent",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="Katıldı sayılması için gereken minimum yüzde",
                        verbose_name="Katılım Eşiği (%)",
                    ),
                ),
                (
                    "minimum_duration_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Katıldı sayılması için gereken minimum süre",
                        verbose_name="Minimum Süre (dk)",
                    ),
                ),
                (
                    "late_join_tolerance_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Geç Katılım Toleransı (dk)"
                    ),
                ),
                (
                    "early_leave_tolerance_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Erken Ayrılış Toleransı (dk)"
                    ),
                ),
                (
                    "lobby_enabled",
                    models.BooleanField(default=True, verbose_name="Bekleme Odası"),
                ),
                (
                    "require_authentication",
                    models.BooleanField(
                        default=True, verbose_name="Kimlik Doğrulama Zorunlu"
                    ),
                ),
                (
                    "allow_guests",
                    models.BooleanField(default=False, verbose_name="Misafir İzni"),
                ),
                (
                    "students_can_share_screen",
                    models.BooleanField(
                        default=False, verbose_name="Öğrenci Ekran Paylaşabilir"
                    ),
                ),
                (
                    "students_can_use_whiteboard",
                    models.BooleanField(
                        default=True, verbose_name="Öğrenci Whiteboard Kullanabilir"
                    ),
                ),
                (
                    "students_can_unmute_self",
                    models.BooleanField(
                        default=True, verbose_name="Öğrenci Kendini Açabilir"
                    ),
                ),
                (
                    "students_start_muted",
                    models.BooleanField(
                        default=True, verbose_name="Öğrenci Sessiz Başlasın"
                    ),
                ),
                (
                    "students_video_off",
                    models.BooleanField(
                        default=False, verbose_name="Öğrenci Kamera Kapalı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_policies",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="live.livesession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_policies",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canlı Ders Politikası",
                "verbose_name_plural": "Canlı Ders Politikaları",
            },
        ),
        migrations.CreateModel(
            name="LiveSessionRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "provider_recording_id",
                    models.CharField(max_length=200, verbose_name="Sağlayıcı Kayıt ID"),
                ),
                (
                    "provider_url",
                    models.URLField(blank=True, verbose_name="Sağlayıcı URL"),
                ),
                (
                    "storage_url",
                    models.URLField(blank=True, verbose_name="Storage URL"),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Storage Path"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Süre (sn)"),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        default=0, verbose_name="Dosya Boyutu (byte)"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        default="mp4", max_length=20, verbose_name="Format"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        help_text="Örn: 1080p, 720p",
                        max_length=20,
                        verbose_name="Çözünürlük",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, verbose_name="Thumbnail URL"),
                ),
                (
                    "transcript_status",
                    models.CharField(
                        choices=[
                            ("none", "Yok"),
                            ("processing", "İşleniyor"),
                            ("ready", "Hazır"),
                            ("failed", "Hata"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Transkript Durumu",
                    ),
                ),
                (
                    "transcript_url",
                    models.URLField(blank=True, verbose_name="Transkript URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "İşleniyor"),
                            ("ready", "Hazır"),
                            ("published", "Yayında"),
                            ("failed", "Hata"),
                            ("deleted", "Silindi"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Herkese Açık"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanma Tarihi"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="İzlenme Sayısı"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="İndirme Sayısı"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_recordings",
                        to="storage.fileupload",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="live.livesession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Kaydı",
                "verbose_name_plural": "Ders Kayıtları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("jitsi", "Jitsi Meet"),
                            ("bbb", "BigBlueButton"),
                            ("zoom", "Zoom"),
                        ],
                        default="jitsi",
                        max_length=20,
                        verbose_name="Sağlayıcı",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan"),
                ),
                (
                    "jitsi_domain",
                    models.CharField(
                        blank=True,
                        help_text="Örn: meet.yourdomain.com",
                        max_length=200,
                        verbose_name="Jitsi Domain",
                    ),
                ),
                (
                    "jitsi_app_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jitsi App ID"
                    ),
                ),
                (
                    "jitsi_jwt_secret",
                    models.CharField(
                        blank=True,
                        help_text="JWT imzalama için gizli anahtar",
                        max_length=500,
                        verbose_name="Jitsi JWT Secret",
                    ),
                ),
                (
                    "bbb_server_url",
                    models.URLField(blank=True, verbose_name="BBB Server URL"),
                ),
                (
                    "bbb_shared_secret",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="BBB Shared Secret"
                    ),
                ),
                (
                    "zoom_account_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zoom Account ID"
                    ),
                ),
                (
                    "zoom_client_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zoom Client ID"
                    ),
                ),
                (
                    "zoom_client_secret",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Zoom Client Secret"
                    ),
                ),
                (
                    "max_concurrent_rooms",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Maksimum Eşzamanlı Oda"
                    ),
                ),
                (
                    "default_room_duration_minutes",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Varsayılan Oda Süresi (dk)"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sağlayıcı Konfigürasyonu",
                "verbose_name_plural": "Sağlayıcı Konfigürasyonları",
                "unique_together": {("tenant", "provider")},
            },
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["status", "scheduled_start"],
                name="live_livese_status_3df47e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["course", "status"], name="live_livese_course__1ce3a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["room_id"], name="live_livese_room_id_0a9612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["provider", "status"], name="live_livese_provide_ae854a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="livesessionattendancesummary",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="livesessionparticipant",
            index=models.Index(
                fields=["session", "user"], name="live_livese_session_80a9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesessionparticipant",
            index=models.Index(
                fields=["session", "is_active"], name="live_livese_session_d40d82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesessionparticipant",
            index=models.Index(
                fields=["joined_at"], name="live_livese_joined__a9e589_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesessionrecording",
            index=models.Index(
                fields=["session", "status"], name="live_livese_session_dc620b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesessionrecording",
            index=models.Index(
                fields=["status", "expires_at"], name="live_livese_status_a552fd_idx"
            ),
        ),
    ]
