# Generated by Django 5.2.9 on 2025-12-26 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="Bağlam"),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mesaj Sayısı"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Aktivite"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="player.playbacksession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Konuşması",
                "verbose_name_plural": "AI Konuşmaları",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Kullanıcı"),
                            ("assistant", "Asistan"),
                            ("system", "Sistem"),
                        ],
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "video_ts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Video Zamanı"
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Kaynaklar"
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Token Kullanımı"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Model"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.aiconversation",
                        verbose_name="Konuşma",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Mesajı",
                "verbose_name_plural": "AI Mesajları",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "daily_questions_limit",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Günlük Soru Limiti"
                    ),
                ),
                (
                    "daily_questions_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Günlük Kullanılan"
                    ),
                ),
                (
                    "monthly_tokens_limit",
                    models.PositiveIntegerField(
                        default=100000, verbose_name="Aylık Token Limiti"
                    ),
                ),
                (
                    "monthly_tokens_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Aylık Token Kullanımı"
                    ),
                ),
                (
                    "daily_reset_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Günlük Reset"
                    ),
                ),
                (
                    "monthly_reset_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aylık Reset"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quota",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Kotası",
                "verbose_name_plural": "AI Kotaları",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True, default="tr", max_length=10, verbose_name="Dil"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Otomatik (AI)"),
                            ("manual", "Manuel"),
                            ("imported", "İçe Aktarılmış"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="Kaynak",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(blank=True, verbose_name="Ham İçerik"),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True, db_index=True, verbose_name="Tam Metin"
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kelime Sayısı"
                    ),
                ),
                (
                    "segment_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Segment Sayısı"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Süre (sn)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transkript",
                "verbose_name_plural": "Transkriptler",
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_ts",
                    models.FloatField(db_index=True, verbose_name="Başlangıç (sn)"),
                ),
                ("end_ts", models.FloatField(verbose_name="Bitiş (sn)")),
                ("text", models.TextField(verbose_name="Metin")),
                (
                    "sequence",
                    models.PositiveIntegerField(db_index=True, verbose_name="Sıra"),
                ),
                (
                    "speaker",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Konuşmacı"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Güven Skoru"
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="ai.transcript",
                        verbose_name="Transkript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transkript Segmenti",
                "verbose_name_plural": "Transkript Segmentleri",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="VideoSummary",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("brief", "Kısa Özet"),
                            ("detailed", "Detaylı Özet"),
                            ("bullet_points", "Madde Madde"),
                            ("key_takeaways", "Önemli Noktalar"),
                            ("chapter", "Bölüm Özeti"),
                        ],
                        default="brief",
                        max_length=20,
                        verbose_name="Özet Türü",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="tr", max_length=10, verbose_name="Dil"),
                ),
                ("summary_text", models.TextField(verbose_name="Özet")),
                (
                    "start_ts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Başlangıç"
                    ),
                ),
                (
                    "end_ts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Bitiş"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(blank=True, max_length=50, verbose_name="Model"),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Token Kullanımı"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Özeti",
                "verbose_name_plural": "Video Özetleri",
            },
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["tenant", "user", "-last_activity_at"],
                name="ai_aiconver_tenant__65e5bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["content", "user"], name="ai_aiconver_content_a8437b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="ai_aimessag_convers_af7707_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["tenant", "content", "language"],
                name="ai_transcri_tenant__737f82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["status"], name="ai_transcri_status_804904_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="transcript",
            unique_together={("content", "language")},
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["transcript", "start_ts"], name="ai_transcri_transcr_219615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videosummary",
            index=models.Index(
                fields=["content", "summary_type", "language"],
                name="ai_videosum_content_e25b8d_idx",
            ),
        ),
    ]
