# Generated by Django 5.2.9 on 2025-12-26 21:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaybackSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Client tarafından üretilen benzersiz cihaz tanımlayıcı",
                        max_length=255,
                        null=True,
                        verbose_name="Cihaz ID",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="GDPR uyumu için hash'lenmiş IP",
                        max_length=64,
                        null=True,
                        verbose_name="IP Hash",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Başlangıç",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                (
                    "ended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ended", "Video Bitti"),
                            ("paused", "Durduruldu"),
                            ("timeout", "Zaman Aşımı"),
                            ("logout", "Çıkış Yapıldı"),
                            ("error", "Hata"),
                            ("navigation", "Sayfa Değişikliği"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Bitiş Nedeni",
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Client'ın son yaşam sinyali",
                        null=True,
                        verbose_name="Son Heartbeat",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Aktif"
                    ),
                ),
                (
                    "last_position_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Son Pozisyon (sn)"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_sessions",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_sessions",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İzleme Oturumu",
                "verbose_name_plural": "İzleme Oturumları",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "user", "content", "-started_at"],
                        name="player_play_tenant__11b1bf_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active", "-started_at"],
                        name="player_play_tenant__700376_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="player_play_user_id_e81776_idx",
                    ),
                ],
            },
        ),
    ]
