# Generated by Django 5.2.9 on 2025-12-26 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "watched_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Seek hariç gerçek izleme süresi",
                        verbose_name="İzlenen Süre (sn)",
                    ),
                ),
                (
                    "last_position_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Videonun kaldığı yer",
                        verbose_name="Son Pozisyon (sn)",
                    ),
                ),
                (
                    "completion_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="0.0000 - 1.0000 arası",
                        max_digits=5,
                        verbose_name="Tamamlanma Oranı",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Tamamlandı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "last_device_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Son Cihaz"
                    ),
                ),
                (
                    "preferred_speed",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="0.5 - 2.0 arası",
                        max_digits=3,
                        verbose_name="Tercih Edilen Hız",
                    ),
                ),
                (
                    "preferred_caption_lang",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Tercih Edilen Altyazı",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "last_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="player.playbacksession",
                        verbose_name="Son Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video İlerlemesi",
                "verbose_name_plural": "Video İlerlemeleri",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressWatchWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_video_ts",
                    models.PositiveIntegerField(
                        help_text="Video başlangıç zamanı",
                        verbose_name="Başlangıç (sn)",
                    ),
                ),
                (
                    "end_video_ts",
                    models.PositiveIntegerField(
                        help_text="Video bitiş zamanı", verbose_name="Bitiş (sn)"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Süre (sn)"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True,
                        help_text="Server tarafından doğrulandı mı?",
                        verbose_name="Doğrulanmış",
                    ),
                ),
                (
                    "playback_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=3,
                        verbose_name="Oynatma Hızı",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_windows",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_windows",
                        to="player.playbacksession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_windows",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_windows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_windows",
                        to="progress.videoprogress",
                        verbose_name="İlerleme",
                    ),
                ),
            ],
            options={
                "verbose_name": "İzleme Penceresi",
                "verbose_name_plural": "İzleme Pencereleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="videoprogress",
            index=models.Index(
                fields=["tenant", "user", "course"],
                name="progress_vi_tenant__a3f886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoprogress",
            index=models.Index(
                fields=["tenant", "content", "is_completed"],
                name="progress_vi_tenant__c82252_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoprogress",
            index=models.Index(
                fields=["user", "is_completed"], name="progress_vi_user_id_fdc563_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="videoprogress",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "content"),
                name="unique_user_content_progress",
            ),
        ),
        migrations.AddIndex(
            model_name="progresswatchwindow",
            index=models.Index(
                fields=["tenant", "session"], name="progress_pr_tenant__31aaf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progresswatchwindow",
            index=models.Index(
                fields=["tenant", "user", "content"],
                name="progress_pr_tenant__4438eb_idx",
            ),
        ),
    ]
