# Generated by Django 5.2.9 on 2025-12-26 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("poll", "Anket"),
                            ("checkpoint", "Kontrol Noktası"),
                            ("hotspot", "Tıklanabilir Bölge"),
                            ("info", "Bilgi Kartı"),
                            ("cta", "Aksiyon Butonu"),
                            ("chapter", "Bölüm"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Node Türü",
                    ),
                ),
                (
                    "start_ts",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Node'un gösterileceği video zamanı",
                        verbose_name="Başlangıç (sn)",
                    ),
                ),
                (
                    "end_ts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Node'un gizleneceği zaman (opsiyonel)",
                        null=True,
                        verbose_name="Bitiş (sn)",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Node türüne göre değişen ayarlar",
                        verbose_name="Konfigürasyon",
                    ),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="Video durdurulup etkileşim beklenir mi?",
                        verbose_name="Engelleyici",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="İlerlemek için tamamlanması zorunlu mu?",
                        verbose_name="Zorunlu",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_nodes",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_nodes",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline Node",
                "verbose_name_plural": "Timeline Nodes",
                "ordering": ["start_ts", "order"],
            },
        ),
        migrations.CreateModel(
            name="TimelineNodeInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("viewed", "Görüntülendi"),
                            ("clicked", "Tıklandı"),
                            ("completed", "Tamamlandı"),
                            ("skipped", "Atlandı"),
                            ("answered", "Cevaplandı"),
                        ],
                        max_length=20,
                        verbose_name="Etkileşim Türü",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Veri"),
                ),
                (
                    "video_ts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Video Zamanı"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="timeline.timelinenode",
                        verbose_name="Node",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_interactions",
                        to="player.playbacksession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Etkileşimi",
                "verbose_name_plural": "Node Etkileşimleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="timelinenode",
            index=models.Index(
                fields=["tenant", "content", "start_ts"],
                name="timeline_ti_tenant__44545d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelinenode",
            index=models.Index(
                fields=["tenant", "content", "node_type"],
                name="timeline_ti_tenant__ed34b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelinenode",
            index=models.Index(
                fields=["content", "is_active", "start_ts"],
                name="timeline_ti_content_b5435d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelinenodeinteraction",
            index=models.Index(
                fields=["tenant", "user", "node"], name="timeline_ti_tenant__a4e2c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinenodeinteraction",
            index=models.Index(
                fields=["node", "interaction_type"],
                name="timeline_ti_node_id_816052_idx",
            ),
        ),
    ]
