# Generated by Django 5.2.9 on 2025-12-26 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentLockPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("min_watch_ratio", "Minimum İzleme"),
                            ("requires_prev_completed", "Önceki Tamamlanmalı"),
                            ("requires_quiz_pass", "Quiz Geçilmeli"),
                            ("requires_checkpoint", "Checkpoint Tamamlanmalı"),
                            ("time_locked", "Zamana Bağlı"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Policy Türü",
                    ),
                ),
                (
                    "policy_config",
                    models.JSONField(
                        default=dict,
                        help_text="Policy türüne göre değişen ayarlar",
                        verbose_name="Policy Ayarları",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Yüksek öncelik önce değerlendirilir",
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_policies",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_policies",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kilit Politikası",
                "verbose_name_plural": "Kilit Politikaları",
                "ordering": ["-priority", "policy_type"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "course", "content"],
                        name="sequencing__tenant__49455d_idx",
                    ),
                    models.Index(
                        fields=["tenant", "content", "is_active"],
                        name="sequencing__tenant__7bc85c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentUnlockState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "is_unlocked",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Açık"
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Açılma Zamanı"
                    ),
                ),
                (
                    "unlock_reason",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Açılma Nedeni",
                    ),
                ),
                (
                    "evaluation_state",
                    models.JSONField(
                        default=dict,
                        help_text="Her policy için değerlendirme sonucu",
                        verbose_name="Değerlendirme Durumu",
                    ),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Değerlendirme"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlock_states",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlock_states",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlock_states",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kilit Durumu",
                "verbose_name_plural": "Kilit Durumları",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "user", "course"],
                        name="sequencing__tenant__aaadb1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "content", "is_unlocked"],
                        name="sequencing__tenant__ea71cb_idx",
                    ),
                    models.Index(
                        fields=["user", "is_unlocked"],
                        name="sequencing__user_id_d13f2a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user", "content"),
                        name="unique_user_content_unlock",
                    )
                ],
            },
        ),
    ]
