# Generated by Django 5.2.9 on 2025-12-26 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFingerprint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint_hash",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Parmak İzi Hash"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="desktop, mobile, tablet",
                        max_length=50,
                        verbose_name="Cihaz Tipi",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="İşletim Sistemi"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tarayıcı"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "screen_resolution",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ekran Çözünürlüğü"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zaman Dilimi"
                    ),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=20, verbose_name="Dil"),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="IP Hash"
                    ),
                ),
                (
                    "trust_score",
                    models.FloatField(
                        default=1.0,
                        help_text="0-1 arası, düşük = şüpheli",
                        verbose_name="Güven Skoru",
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(default=True, verbose_name="Güvenilir"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Engellendi"),
                ),
                (
                    "session_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Oturum Sayısı"
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="İlk Görülme"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Görülme"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_fingerprints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cihaz Parmak İzi",
                "verbose_name_plural": "Cihaz Parmak İzleri",
            },
        ),
        migrations.CreateModel(
            name="IntegrityCheck",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Geçti"),
                            ("warning", "Uyarı"),
                            ("failed", "Başarısız"),
                        ],
                        default="passed",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "visibility_score",
                    models.FloatField(
                        default=1.0,
                        help_text="Tab aktif olma oranı",
                        verbose_name="Görünürlük Skoru",
                    ),
                ),
                (
                    "playback_score",
                    models.FloatField(
                        default=1.0,
                        help_text="Normal oynatma davranışı",
                        verbose_name="Oynatma Skoru",
                    ),
                ),
                (
                    "timing_score",
                    models.FloatField(
                        default=1.0,
                        help_text="İzleme süresi tutarlılığı",
                        verbose_name="Zamanlama Skoru",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(default=1.0, verbose_name="Genel Skor"),
                ),
                (
                    "checks_performed",
                    models.JSONField(default=list, verbose_name="Yapılan Kontroller"),
                ),
                (
                    "video_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Video Pozisyonu"
                    ),
                ),
                (
                    "client_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Client Verisi"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrity_checks",
                        to="integrity.devicefingerprint",
                        verbose_name="Cihaz",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_checks",
                        to="player.playbacksession",
                        verbose_name="Oynatma Oturumu",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütünlük Kontrolü",
                "verbose_name_plural": "Bütünlük Kontrolleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrityConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "min_visibility_score",
                    models.FloatField(
                        default=0.7, verbose_name="Min. Görünürlük Skoru"
                    ),
                ),
                (
                    "min_playback_score",
                    models.FloatField(default=0.6, verbose_name="Min. Oynatma Skoru"),
                ),
                (
                    "min_overall_score",
                    models.FloatField(default=0.5, verbose_name="Min. Genel Skor"),
                ),
                (
                    "max_anomalies_per_session",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Oturum Başına Max. Anomali"
                    ),
                ),
                (
                    "max_anomalies_per_day",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Günlük Max. Anomali"
                    ),
                ),
                (
                    "auto_restrict_threshold",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Bu skorun altına düşerse kısıtla",
                        verbose_name="Otomatik Kısıtlama Eşiği",
                    ),
                ),
                (
                    "check_interval",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Kontrol Aralığı (sn)"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütünlük Yapılandırması",
                "verbose_name_plural": "Bütünlük Yapılandırmaları",
            },
        ),
        migrations.CreateModel(
            name="PlaybackAnomaly",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("speed", "Hız Manipülasyonu"),
                            ("seek", "Aşırı Atlama"),
                            ("tab", "Tab Pasif"),
                            ("timing", "Zamanlama Uyuşmazlığı"),
                            ("multi_device", "Çoklu Cihaz"),
                            ("rapid", "Hızlı Tamamlama"),
                            ("jump", "Pozisyon Atlama"),
                            ("hijack", "Oturum Ele Geçirme"),
                        ],
                        max_length=20,
                        verbose_name="Anomali Türü",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("critical", "Kritik"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Şiddet",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("details", models.JSONField(default=dict, verbose_name="Detaylar")),
                (
                    "video_ts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Video Zamanı"
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, verbose_name="İncelendi"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İnceleme Zamanı"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="İnceleme Notları"),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Alınan Aksiyon"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_anomalies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İnceleyen",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="player.playbacksession",
                        verbose_name="Oynatma Oturumu",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_anomalies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oynatma Anomalisi",
                "verbose_name_plural": "Oynatma Anomalileri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserIntegrityScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=100, verbose_name="Skor"),
                ),
                (
                    "total_checks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Kontrol"
                    ),
                ),
                (
                    "passed_checks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Geçen Kontrol"
                    ),
                ),
                (
                    "failed_checks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Başarısız Kontrol"
                    ),
                ),
                (
                    "anomaly_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Anomali Sayısı"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="low",
                        help_text="low, medium, high",
                        max_length=20,
                        verbose_name="Risk Seviyesi",
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(default=False, verbose_name="Kısıtlı"),
                ),
                (
                    "restriction_reason",
                    models.TextField(blank=True, verbose_name="Kısıtlama Nedeni"),
                ),
                (
                    "restricted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kısıtlama Zamanı"
                    ),
                ),
                (
                    "last_check_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kontrol"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_score",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Bütünlük Skoru",
                "verbose_name_plural": "Kullanıcı Bütünlük Skorları",
            },
        ),
        migrations.AddIndex(
            model_name="devicefingerprint",
            index=models.Index(
                fields=["tenant", "user", "is_trusted"],
                name="integrity_d_tenant__4f56e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicefingerprint",
            index=models.Index(
                fields=["fingerprint_hash"], name="integrity_d_fingerp_8800f3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicefingerprint",
            unique_together={("tenant", "user", "fingerprint_hash")},
        ),
        migrations.AddIndex(
            model_name="integritycheck",
            index=models.Index(
                fields=["tenant", "session", "-created_at"],
                name="integrity_i_tenant__cbf32e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integritycheck",
            index=models.Index(
                fields=["tenant", "user", "status"],
                name="integrity_i_tenant__dcf670_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playbackanomaly",
            index=models.Index(
                fields=["tenant", "user", "-created_at"],
                name="integrity_p_tenant__2021ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playbackanomaly",
            index=models.Index(
                fields=["tenant", "anomaly_type", "severity"],
                name="integrity_p_tenant__1ec368_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playbackanomaly",
            index=models.Index(
                fields=["is_reviewed"], name="integrity_p_is_revi_065f3e_idx"
            ),
        ),
    ]
