# Generated by Django 5.2.9 on 2025-12-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fileupload",
            new_name="storage_fil_categor_589a08_idx",
            old_name="storage_fil_categor_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="fileupload",
            new_name="storage_fil_uploade_1cf656_idx",
            old_name="storage_fil_uploade_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="fileupload",
            new_name="storage_fil_content_0e24c7_idx",
            old_name="storage_fil_content_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="fileupload",
            new_name="storage_fil_file_ha_a705bf_idx",
            old_name="storage_fil_file_ha_j0k1l2_idx",
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
    ]
