# Generated by Django 5.2.9 on 2025-12-26 21:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("player", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        choices=[
                            ("heatmap", "Isı Haritası"),
                            ("dropoff", "Drop-off"),
                            ("rewind", "Geri Sarma"),
                            ("skip", "Atlama"),
                            ("engagement", "Etkileşim"),
                        ],
                        max_length=20,
                        verbose_name="Özet Türü",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Dönem Başlangıcı")),
                ("period_end", models.DateTimeField(verbose_name="Dönem Bitişi")),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Türe göre değişen özet verileri",
                        verbose_name="Özet Verisi",
                    ),
                ),
                (
                    "sample_count",
                    models.PositiveIntegerField(default=0, verbose_name="Örnek Sayısı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_aggregates",
                        to="courses.coursecontent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_aggregates",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telemetry Özeti",
                "verbose_name_plural": "Telemetry Özetleri",
                "ordering": ["-period_end"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "content", "aggregate_type"],
                        name="telemetry_t_tenant__0e25b7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_event_id",
                    models.CharField(
                        help_text="Client tarafından üretilen benzersiz event ID",
                        max_length=100,
                        verbose_name="Client Event ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("play", "Oynat"),
                            ("pause", "Durdur"),
                            ("seek", "Atla"),
                            ("seeked", "Atlama Tamamlandı"),
                            ("timeupdate", "Zaman Güncelleme"),
                            ("ended", "Bitti"),
                            ("rate_change", "Hız Değişimi"),
                            ("fullscreen", "Tam Ekran"),
                            ("pip", "Picture-in-Picture"),
                            ("buffer_start", "Buffer Başladı"),
                            ("buffer_end", "Buffer Bitti"),
                            ("error", "Hata"),
                            ("quality_change", "Kalite Değişimi"),
                            ("visibility_change", "Görünürlük Değişimi"),
                            ("volume_change", "Ses Değişimi"),
                            ("caption_change", "Altyazı Değişimi"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Event Türü",
                    ),
                ),
                (
                    "video_ts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Event anındaki video pozisyonu",
                        null=True,
                        verbose_name="Video Zamanı (sn)",
                    ),
                ),
                (
                    "server_ts",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Server Zamanı",
                    ),
                ),
                (
                    "client_ts",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Client Zamanı"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        help_text="Event'e özgü ek veriler",
                        null=True,
                        verbose_name="Payload",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to="player.playbacksession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telemetry Event",
                "verbose_name_plural": "Telemetry Events",
                "ordering": ["-server_ts"],
                "indexes": [
                    models.Index(
                        fields=["session", "-server_ts"],
                        name="telemetry_t_session_f3055e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "content", "event_type", "-server_ts"],
                        name="telemetry_t_tenant__c39657_idx",
                    ),
                    models.Index(
                        fields=["tenant", "user", "-server_ts"],
                        name="telemetry_t_tenant__91b328_idx",
                    ),
                    models.Index(
                        fields=["tenant", "event_type", "-server_ts"],
                        name="telemetry_t_tenant__99ab90_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "session", "client_event_id"),
                        name="unique_telemetry_event",
                    )
                ],
            },
        ),
    ]
