# Generated by Django 5.2.9 on 2025-12-24 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-posta"
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=150, verbose_name="Soyad")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GUEST", "Misafir"),
                            ("STUDENT", "Öğrenci"),
                            ("INSTRUCTOR", "Eğitmen"),
                            ("ADMIN", "Yönetici"),
                            ("TENANT_ADMIN", "Kurum Yöneticisi"),
                            ("SUPER_ADMIN", "Süper Admin"),
                        ],
                        db_index=True,
                        default="GUEST",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        help_text="Profil fotoğrafı URL'i",
                        null=True,
                        verbose_name="Profil Fotoğrafı",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Örn: Kıdemli Yazılım Mühendisi",
                        max_length=100,
                        verbose_name="Ünvan",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Kısa biyografi", verbose_name="Hakkında"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, help_text="Toplanan XP puanı", verbose_name="Puan"
                    ),
                ),
                (
                    "streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Ardışık gün sayısı", verbose_name="Seri"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Türkçe"), ("en", "English")],
                        default="tr",
                        max_length=5,
                        verbose_name="Dil",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Istanbul",
                        max_length=50,
                        verbose_name="Saat Dilimi",
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        default=True, verbose_name="E-posta Bildirimleri"
                    ),
                ),
                (
                    "notify_push",
                    models.BooleanField(default=True, verbose_name="Push Bildirimleri"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Son Giriş IP"
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="E-posta Doğrulama Tarihi"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="tenants.tenant",
                        verbose_name="Akademi",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Öğrenci No"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="Bölüm"),
                ),
                (
                    "expertise_areas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Uzmanlık Alanları"
                    ),
                ),
                (
                    "certificates",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Sertifikalar"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["tenant"], name="users_user_tenant__79c011_idx"),
        ),
    ]
