# Generated by Django 5.2.9 on 2025-12-26 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("personalized", "Kişiselleştirilmiş"),
                            ("similar", "Benzer İçerik"),
                            ("trending", "Trend"),
                            ("next", "Sonraki Önerilen"),
                            ("continue", "Devam Et"),
                            ("new", "Yeni İçerik"),
                        ],
                        max_length=20,
                        verbose_name="Öneri Türü",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Model tarafından hesaplanan skor",
                        verbose_name="Öneri Skoru",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Öneri listesindeki sıra", verbose_name="Sıra"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Kullanıcıya gösterilebilir açıklama",
                        verbose_name="Öneri Nedeni",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Model Versiyonu"
                    ),
                ),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="Bağlam"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("shown", "Gösterildi"),
                            ("clicked", "Tıklandı"),
                            ("started", "Başlandı"),
                            ("completed", "Tamamlandı"),
                            ("dismissed", "Reddedildi"),
                        ],
                        default="shown",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "shown_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gösterilme Zamanı"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tıklanma Zamanı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Zamanı"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öneri",
                "verbose_name_plural": "Öneriler",
                "ordering": ["-shown_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Faydalı"),
                            ("not_helpful", "Faydalı Değil"),
                            ("not_interested", "İlgilenmiyorum"),
                            ("already_know", "Zaten Biliyorum"),
                            ("too_easy", "Çok Kolay"),
                            ("too_hard", "Çok Zor"),
                            ("wrong_topic", "Yanlış Konu"),
                        ],
                        max_length=20,
                        verbose_name="Geri Bildirim Türü",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Yorum")),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="recommendations.recommendation",
                        verbose_name="Öneri",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öneri Geri Bildirimi",
                "verbose_name_plural": "Öneri Geri Bildirimleri",
            },
        ),
        migrations.CreateModel(
            name="TrendingContent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                        ],
                        max_length=20,
                        verbose_name="Periyot",
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Sıra")),
                ("score", models.FloatField(verbose_name="Trend Skoru")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                (
                    "completion_count",
                    models.PositiveIntegerField(default=0, verbose_name="Tamamlama"),
                ),
                (
                    "engagement_score",
                    models.FloatField(default=0.0, verbose_name="Etkileşim Skoru"),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Hesaplama Zamanı"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_entries",
                        to="courses.coursecontent",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend İçerik",
                "verbose_name_plural": "Trend İçerikler",
                "ordering": ["period", "rank"],
            },
        ),
        migrations.CreateModel(
            name="UserContentInterest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_scores",
                    models.JSONField(
                        default=dict,
                        help_text='{"kategori_id": skor, ...}',
                        verbose_name="Kategori Skorları",
                    ),
                ),
                (
                    "tag_scores",
                    models.JSONField(
                        default=dict,
                        help_text='{"tag": skor, ...}',
                        verbose_name="Etiket Skorları",
                    ),
                ),
                (
                    "instructor_scores",
                    models.JSONField(
                        default=dict,
                        help_text='{"instructor_id": skor, ...}',
                        verbose_name="Eğitmen Skorları",
                    ),
                ),
                (
                    "preferred_duration",
                    models.CharField(
                        blank=True,
                        help_text="short (<10dk), medium (10-30dk), long (>30dk)",
                        max_length=20,
                        null=True,
                        verbose_name="Tercih Edilen Süre",
                    ),
                ),
                (
                    "preferred_difficulty",
                    models.CharField(
                        blank=True,
                        help_text="beginner, intermediate, advanced",
                        max_length=20,
                        null=True,
                        verbose_name="Tercih Edilen Zorluk",
                    ),
                ),
                (
                    "active_hours",
                    models.JSONField(
                        default=dict,
                        help_text='{"saat": kullanım_sayısı, ...}',
                        verbose_name="Aktif Saatler",
                    ),
                ),
                (
                    "total_watch_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam İzleme Süresi (dk)"
                    ),
                ),
                (
                    "total_completions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Tamamlama"
                    ),
                ),
                (
                    "avg_completion_rate",
                    models.FloatField(
                        default=0.0, verbose_name="Ortalama Tamamlama Oranı"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Aktivite"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_interests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı İlgi Profili",
                "verbose_name_plural": "Kullanıcı İlgi Profilleri",
            },
        ),
        migrations.CreateModel(
            name="ContentSimilarity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(db_index=True, verbose_name="Benzerlik Skoru"),
                ),
                (
                    "similarity_type",
                    models.CharField(
                        default="content_based",
                        help_text="content_based, collaborative, hybrid",
                        max_length=50,
                        verbose_name="Benzerlik Tipi",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Hesaplama Zamanı"
                    ),
                ),
                (
                    "content_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_a",
                        to="courses.coursecontent",
                        verbose_name="İçerik A",
                    ),
                ),
                (
                    "content_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_b",
                        to="courses.coursecontent",
                        verbose_name="İçerik B",
                    ),
                ),
            ],
            options={
                "verbose_name": "İçerik Benzerliği",
                "verbose_name_plural": "İçerik Benzerlikleri",
                "indexes": [
                    models.Index(
                        fields=["content_a", "similarity_score"],
                        name="recommendat_content_e4a89d_idx",
                    ),
                    models.Index(
                        fields=["content_b", "similarity_score"],
                        name="recommendat_content_7e51ed_idx",
                    ),
                ],
                "unique_together": {("content_a", "content_b", "similarity_type")},
            },
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["tenant", "user", "-shown_at"],
                name="recommendat_tenant__306aef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["tenant", "user", "recommendation_type"],
                name="recommendat_tenant__d95512_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["status"], name="recommendat_status_d2897f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationfeedback",
            unique_together={("recommendation", "user")},
        ),
        migrations.AddIndex(
            model_name="trendingcontent",
            index=models.Index(
                fields=["tenant", "period", "rank"],
                name="recommendat_tenant__c2dd47_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trendingcontent",
            unique_together={("tenant", "content", "period")},
        ),
        migrations.AddIndex(
            model_name="usercontentinterest",
            index=models.Index(
                fields=["tenant", "user"], name="recommendat_tenant__0d5700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercontentinterest",
            index=models.Index(
                fields=["last_activity_at"], name="recommendat_last_ac_d1c4e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercontentinterest",
            unique_together={("tenant", "user")},
        ),
    ]
