# Generated by Django 5.2.9 on 2025-12-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "İçerik İlerlemesi",
                "verbose_name_plural": "İçerik İlerlemeleri",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("slug", models.SlugField(unique=True, verbose_name="URL Slug")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Kısa Açıklama"
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(blank=True, verbose_name="Kapak Görseli"),
                ),
                ("category", models.CharField(max_length=100, verbose_name="Kategori")),
                (
                    "language",
                    models.CharField(default="tr", max_length=10, verbose_name="Dil"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Başlangıç"),
                            ("Intermediate", "Orta"),
                            ("Advanced", "İleri"),
                        ],
                        default="Beginner",
                        max_length=20,
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Etiketler"
                    ),
                ),
                ("is_free", models.BooleanField(default=True, verbose_name="Ücretsiz")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Fiyat"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("TRY", "₺"), ("USD", "$"), ("EUR", "€")],
                        default="TRY",
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Herkese Açık"),
                            ("private", "Özel"),
                            ("unlisted", "Listelenmemiş"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Görünürlük",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Yayında"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "certificate_enabled",
                    models.BooleanField(default=True, verbose_name="Sertifika Aktif"),
                ),
                (
                    "completion_percent",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Sertifika için gereken minimum tamamlama yüzdesi",
                        verbose_name="Tamamlama Yüzdesi",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(blank=True, verbose_name="Karşılama Mesajı"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("pending_admin_setup", "Admin Onayı Bekliyor"),
                            ("needs_revision", "Düzenleme Gerekli"),
                            ("published", "Yayında"),
                            ("archived", "Arşivlenmiş"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "teacher_submit_note",
                    models.TextField(
                        blank=True,
                        help_text="Eğitmenin admin'e notu",
                        verbose_name="Eğitmen Notu",
                    ),
                ),
                (
                    "admin_revision_note",
                    models.TextField(
                        blank=True,
                        help_text="Admin'in düzenleme talebi",
                        verbose_name="Admin Düzenleme Notu",
                    ),
                ),
                (
                    "enrolled_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kayıtlı Öğrenci"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Puan"
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Değerlendirme Sayısı"
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Toplam Süre (dk)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Döküman"),
                            ("QUIZ", "Quiz"),
                            ("ASSIGNMENT", "Ödev"),
                            ("EXAM", "Sınav"),
                            ("LIVE", "Canlı Ders"),
                            ("TEXT", "Metin"),
                            ("LINK", "Link"),
                        ],
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Video URL, döküman path, quiz soruları vb.",
                        verbose_name="İçerik Verisi",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Süre (dk)"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Önceki içerikler tamamlanmadan erişilemez",
                        verbose_name="Kilitli",
                    ),
                ),
                (
                    "is_ready",
                    models.BooleanField(
                        default=False,
                        help_text="İçerik tamamlandı mı?",
                        verbose_name="Hazır",
                    ),
                ),
                (
                    "is_free_preview",
                    models.BooleanField(
                        default=False, verbose_name="Ücretsiz Önizleme"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "İçerik",
                "verbose_name_plural": "İçerikler",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayında"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modül",
                "verbose_name_plural": "Modüller",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("completed", "Tamamlandı"),
                            ("expired", "Süresi Doldu"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveIntegerField(default=0, verbose_name="İlerleme %"),
                ),
                (
                    "completed_contents",
                    models.JSONField(
                        default=list,
                        help_text="Tamamlanan içerik ID listesi",
                        verbose_name="Tamamlanan İçerikler",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Kayıt",
                "verbose_name_plural": "Kayıtlar",
                "ordering": ["-enrolled_at"],
            },
        ),
    ]
