# Generated by Django 5.2.9 on 2025-12-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="teaching_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eğitmenler",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="tenants.tenant",
                verbose_name="Akademi",
            ),
        ),
        migrations.AddField(
            model_name="contentprogress",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="courses.coursecontent",
            ),
        ),
        migrations.AddField(
            model_name="coursemodule",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
                verbose_name="Kurs",
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="courses.coursemodule",
                verbose_name="Modül",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
                verbose_name="Kurs",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_accessed_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="courses.coursecontent",
                verbose_name="Son Erişilen İçerik",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Öğrenci",
            ),
        ),
        migrations.AddField(
            model_name="contentprogress",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_progress",
                to="courses.enrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="courses_cou_slug_2e551f_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="courses_cou_status_158bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["tenant", "status"], name="courses_cou_tenant__8dfec9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursemodule",
            unique_together={("course", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="contentprogress",
            unique_together={("enrollment", "content")},
        ),
    ]
